export const REGISTER_REQUEST = "USERS_REGISTER_REQUEST";
export const REGISTER_SUCCESS = "USERS_REGISTER_SUCCESS";
export const REGISTER_FAILURE = "USERS_REGISTER_FAILURE";

export const LOGIN_REQUEST = "USERS_LOGIN_REQUEST";
export const LOGIN_SUCCESS = "USERS_LOGIN_SUCCESS";
export const LOGIN_FAILURE = "USERS_LOGIN_FAILURE";

export const LOGOUT = "USERS_LOGOUT";

export const GETALL_REQUEST = "USERS_GETALL_REQUEST";
export const GETALL_SUCCESS = "USERS_GETALL_SUCCESS";
export const GETALL_FAILURE = "USERS_GETALL_FAILURE";

export const CURRENT_USER_SUCCESS = "CURRENT_USER_SUCCESS";

export const PRODUCED_COIL_LIST = "PRODUCED_COIL_LIST";
export const PRODUCED_COIL_LIST_REQUEST = "PRODUCED_COIL_LIST";

export const PRODUCED_COIL_FIELDS_BY_ID = "PRODUCED_COIL_FIELDS_BY_ID";
